title: MSU Language Acquisition Lab
description: Online Documentation
theme: just-the-docs

url: https://www.msuacquisition.org/online-documentation/

logo: "/assets/images/lab-logo-with-text.png"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
