title: MSU Language Acquisition Lab
description: Online Documentation
theme: just-the-docs

url: https://www.msuacquisition.org/online-documentation/

logo: "/online-documentation/assets/images/lab-logo-with-text.png"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
